const shopItems = [
  {
    id: "aslkdfjlaksdf",
    name: "casual shirt",
    price: "1550",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://5.imimg.com/data5/SELLER/Default/2022/6/HP/HD/BV/152312210/6-3-500x500.jpg",
  },
  {
    id: "aslkdwoiaksdf",
    name: "formal shirt",
    price: "2240",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://images.unsplash.com/photo-1598032895397-b9472444bf93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hpcnR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: "apqidwoiaksdf",
    name: "t shirt",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://images.unsplash.com/photo-1562157873-818bc0726f68?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNoaXJ0fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: "aslkdwoiakaks",
    name: "suit",
    price: "9999",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://upload.wikimedia.org/wikipedia/commons/7/7d/HD-wallpaper-hitman-cool-designs-naqvi-suit.jpg",
  },
  {
    id: "aslkzwbiakaks",
    name: "hoodie",
    price: "2999",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://assets.ajio.com/medias/sys_master/root/20230623/x1wX/64950899d55b7d0c63af7a26/-1117Wx1400H-464884832-black-MODEL.jpg",
  },
  {
    id: "aslkzwbiapecs",
    name: "jacket",
    price: "3499",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://4.imimg.com/data4/RU/VC/MY-11853389/men-s-jackets.jpg",
  },
  {
    id: "aslkzwnwupecs",
    name: "kurtha",
    price: "4799",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://www.sakhifashions.com/cdn/shop/products/200610_Kurtha_1024x.jpg?v=1592058395",
  },
  {
    id: "accczwnwupecs",
    name: "gym t-shirt",
    price: "999",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://images.meesho.com/images/products/56208093/tdr50_512.webp",
  },
  {
    id: "accczdddupecs",
    name: "sports wear",
    price: "799",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://www.polestargarments.com/wp-content/uploads/2020/11/Sports-wear-13.jpg",
  },
  {
    id: "acccabbdupecs",
    name: "jersey",
    price: "1399",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: "https://m.media-amazon.com/images/I/4193sbk6FFL._AC_UY1100_.jpg",
  },
];
